/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import backend.jsonParser;
import backend.trocarPainel;
import backend.FichaVO;
import org.json.JSONObject;

/**
 *
 * @author Admin
 */
public class personagemFicha extends javax.swing.JFrame {
    
    FichaVO FichaVo = new FichaVO();

    /**
     * Creates new form personagemFicha
     */
    public personagemFicha(String personagem) {
        initComponents();
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        String personagemCaminho = "personagensJSON/" + personagem + ".json";
        jsonParser leitor = new jsonParser();
        JSONObject ficha = new JSONObject(leitor.LerArquivo(personagemCaminho));        
        
        FichaVo.JanelaP(jPanel1);
        FichaVo.StatusP(personagemCaminho, ForLabel, ForMod, ficha, 0);
        FichaVo.StatusP(personagemCaminho, DesLabel, DesMod, ficha, 1);
        FichaVo.StatusP(personagemCaminho, ConLabel, ConMod, ficha, 2);
        FichaVo.StatusP(personagemCaminho, IntLabel, IntMod, ficha, 3);
        FichaVo.StatusP(personagemCaminho, CarLabel, CarMod, ficha, 4);
        FichaVo.StatusP(personagemCaminho, SabLabel, SabMod, ficha, 5);
        FichaVo.PericiasP(personagemCaminho, ficha, ForResCheck, ForResMod, 0);
        FichaVo.PericiasP(personagemCaminho, ficha, DesResCheck, DesResMod, 1);
        FichaVo.PericiasP(personagemCaminho, ficha, ConResCheck, ConResMod, 2);
        FichaVo.PericiasP(personagemCaminho, ficha, IntResCheck, IntResMod, 3);
        FichaVo.PericiasP(personagemCaminho, ficha, SabResCheck, SabResMod, 4);
        FichaVo.PericiasP(personagemCaminho, ficha, CarResCheck, CarResMod, 5);
        FichaVo.ProfP(ficha, BonusProficienciaLabel);
        FichaVo.VidaP(personagemCaminho, ficha, VidaAtual, VidaTotal, VidaCura, VidaDano);
        FichaVo.SalvarP(ficha, salvarBotao, personagemCaminho);
        FichaVo.NomeP(personagemCaminho, ficha, LabelNome);
        FichaVo.ClassesP(personagemCaminho, ficha, ClasseLabel, ClasseLabel, personagem, LevelLabel);
        FichaVo.RacaP(personagemCaminho, ficha, RacaSelect);
        FichaVo.XpP(personagemCaminho, ficha, XpLabel);
        FichaVo.AntecedenteP(personagemCaminho, ficha, AntecedenteLabel);
         

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelNome = new javax.swing.JTextField();
        salvarBotao = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ForMod = new javax.swing.JLabel();
        DesMod = new javax.swing.JLabel();
        ConMod = new javax.swing.JLabel();
        IntMod = new javax.swing.JLabel();
        SabMod = new javax.swing.JLabel();
        CarMod = new javax.swing.JLabel();
        ForLabel = new javax.swing.JTextField();
        DesLabel = new javax.swing.JTextField();
        ConLabel = new javax.swing.JTextField();
        IntLabel = new javax.swing.JTextField();
        SabLabel = new javax.swing.JTextField();
        CarLabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ClassesRow = new javax.swing.JPanel();
        ClasseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        VidaTotal = new javax.swing.JTextField();
        VidaAtual = new javax.swing.JTextField();
        VidaDano = new javax.swing.JLabel();
        VidaCura = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RacaSelect = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        XpLabel = new javax.swing.JTextField();
        AntecedenteLabel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ForResCheck = new javax.swing.JCheckBox();
        DesResCheck = new javax.swing.JCheckBox();
        ConResCheck = new javax.swing.JCheckBox();
        IntResCheck = new javax.swing.JCheckBox();
        SabResCheck = new javax.swing.JCheckBox();
        CarResCheck = new javax.swing.JCheckBox();
        ForResMod = new javax.swing.JLabel();
        DesResMod = new javax.swing.JLabel();
        ConResMod = new javax.swing.JLabel();
        IntResMod = new javax.swing.JLabel();
        SabResMod = new javax.swing.JLabel();
        CarResMod = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        BonusProficienciaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(672, 681));

        jPanel1.setBackground(new java.awt.Color(35, 35, 35));

        jPanel2.setBackground(new java.awt.Color(23, 23, 23));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(35, 35, 195), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 600));

        jButton1.setBackground(new java.awt.Color(79, 79, 79));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("voltar para seleção");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(35, 35, 195));
        jSeparator1.setForeground(new java.awt.Color(35, 35, 195));

        LabelNome.setBackground(new java.awt.Color(23, 23, 23));
        LabelNome.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        LabelNome.setForeground(new java.awt.Color(255, 255, 255));
        LabelNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LabelNome.setText("Nome");
        LabelNome.setBorder(null);
        LabelNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelNomeActionPerformed(evt);
            }
        });

        salvarBotao.setBackground(new java.awt.Color(79, 79, 79));
        salvarBotao.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        salvarBotao.setForeground(new java.awt.Color(255, 255, 255));
        salvarBotao.setText("Salvar alterações");
        salvarBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carisma");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 30));

        jLabel7.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sabedoria");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, 30));

        jLabel9.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Inteligência");
        jLayeredPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        jLabel11.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Constituição");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, 30));

        jLabel13.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Destreza");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jLabel15.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Força");
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        ForMod.setForeground(new java.awt.Color(255, 255, 255));
        ForMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForMod.setText("0");
        jLayeredPane1.add(ForMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 20, 24));

        DesMod.setForeground(new java.awt.Color(255, 255, 255));
        DesMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesMod.setText("0");
        jLayeredPane1.add(DesMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 20, 24));

        ConMod.setForeground(new java.awt.Color(255, 255, 255));
        ConMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConMod.setText("0");
        jLayeredPane1.add(ConMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 20, 24));

        IntMod.setForeground(new java.awt.Color(255, 255, 255));
        IntMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntMod.setText("0");
        jLayeredPane1.add(IntMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 20, 24));

        SabMod.setForeground(new java.awt.Color(255, 255, 255));
        SabMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SabMod.setText("0");
        jLayeredPane1.add(SabMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 20, 24));

        CarMod.setForeground(new java.awt.Color(255, 255, 255));
        CarMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarMod.setText("0");
        jLayeredPane1.add(CarMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 20, 24));

        ForLabel.setBackground(new java.awt.Color(23, 23, 23));
        ForLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ForLabel.setForeground(new java.awt.Color(255, 255, 255));
        ForLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ForLabel.setText("10");
        ForLabel.setBorder(null);
        ForLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ForLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        ForLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForLabelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ForLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 70));

        DesLabel.setBackground(new java.awt.Color(23, 23, 23));
        DesLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        DesLabel.setForeground(new java.awt.Color(255, 255, 255));
        DesLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DesLabel.setText("10");
        DesLabel.setBorder(null);
        DesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DesLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(DesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 70));

        ConLabel.setBackground(new java.awt.Color(23, 23, 23));
        ConLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ConLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ConLabel.setText("10");
        ConLabel.setBorder(null);
        ConLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ConLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(ConLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, 70));

        IntLabel.setBackground(new java.awt.Color(23, 23, 23));
        IntLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        IntLabel.setForeground(new java.awt.Color(255, 255, 255));
        IntLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IntLabel.setText("10");
        IntLabel.setBorder(null);
        IntLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IntLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(IntLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 70));

        SabLabel.setBackground(new java.awt.Color(23, 23, 23));
        SabLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        SabLabel.setForeground(new java.awt.Color(255, 255, 255));
        SabLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SabLabel.setText("10");
        SabLabel.setBorder(null);
        SabLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SabLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(SabLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 70));

        CarLabel.setBackground(new java.awt.Color(23, 23, 23));
        CarLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        CarLabel.setForeground(new java.awt.Color(255, 255, 255));
        CarLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarLabel.setText("10");
        CarLabel.setBorder(null);
        CarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CarLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(CarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 100, 100));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 100));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        ClassesRow.setBackground(new java.awt.Color(23, 23, 23));

        ClasseLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ClasseLabel.setForeground(new java.awt.Color(101, 172, 219));
        ClasseLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClasseLabel.setText("Selecione a sua classe");
        ClasseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Classe:");

        javax.swing.GroupLayout ClassesRowLayout = new javax.swing.GroupLayout(ClassesRow);
        ClassesRow.setLayout(ClassesRowLayout);
        ClassesRowLayout.setHorizontalGroup(
            ClassesRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClassesRowLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(ClasseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        ClassesRowLayout.setVerticalGroup(
            ClassesRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClasseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClassesRowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setOpaque(false);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("/");

        VidaTotal.setBackground(new java.awt.Color(23, 23, 23));
        VidaTotal.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        VidaTotal.setForeground(new java.awt.Color(255, 255, 255));
        VidaTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        VidaTotal.setText("0");
        VidaTotal.setBorder(null);
        VidaTotal.setMinimumSize(new java.awt.Dimension(104, 64));
        VidaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaTotalActionPerformed(evt);
            }
        });

        VidaAtual.setBackground(new java.awt.Color(23, 23, 23));
        VidaAtual.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        VidaAtual.setForeground(new java.awt.Color(255, 255, 255));
        VidaAtual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        VidaAtual.setText("0");
        VidaAtual.setBorder(null);
        VidaAtual.setMinimumSize(new java.awt.Dimension(104, 64));
        VidaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(VidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel39)
                .addGap(0, 0, 0)
                .addComponent(VidaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(VidaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        VidaDano.setForeground(new java.awt.Color(255, 255, 255));
        VidaDano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VidaDano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/down.png"))); // NOI18N
        VidaDano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        VidaCura.setForeground(new java.awt.Color(255, 255, 255));
        VidaCura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VidaCura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/up.png"))); // NOI18N
        VidaCura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Raça:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nível:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Antecedente:");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Xp:");

        RacaSelect.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        RacaSelect.setForeground(new java.awt.Color(101, 172, 219));
        RacaSelect.setText("Selecione");
        RacaSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LevelLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        LevelLabel.setForeground(new java.awt.Color(101, 172, 219));
        LevelLabel.setText("Selecione");

        XpLabel.setBackground(new java.awt.Color(23, 23, 23));
        XpLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        XpLabel.setForeground(new java.awt.Color(255, 255, 255));
        XpLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        XpLabel.setText("0");
        XpLabel.setBorder(null);

        AntecedenteLabel.setBackground(new java.awt.Color(23, 23, 23));
        AntecedenteLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        AntecedenteLabel.setForeground(new java.awt.Color(101, 172, 219));
        AntecedenteLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AntecedenteLabel.setText("Digite seu antecedente");
        AntecedenteLabel.setBorder(null);
        AntecedenteLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntecedenteLabelActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(23, 23, 23));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 195), 2, true));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Pericias:");

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));

        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("0");

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("0");

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("0");

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("0");

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("0");

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("0");

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("0");

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(25, 25, 25))
                            .addComponent(jLabel26))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(25, 25, 25))
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(25, 25, 25))
                            .addComponent(jLabel30))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(25, 25, 25))
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(23, 23, 23));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 195), 2, true));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Testes de resistência:");

        ForResCheck.setForeground(new java.awt.Color(255, 255, 255));

        DesResCheck.setForeground(new java.awt.Color(255, 255, 255));
        DesResCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesResCheckActionPerformed(evt);
            }
        });

        ConResCheck.setForeground(new java.awt.Color(255, 255, 255));

        IntResCheck.setForeground(new java.awt.Color(255, 255, 255));

        SabResCheck.setForeground(new java.awt.Color(255, 255, 255));

        CarResCheck.setForeground(new java.awt.Color(255, 255, 255));

        ForResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ForResMod.setForeground(new java.awt.Color(255, 255, 255));
        ForResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForResMod.setText("0");

        DesResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        DesResMod.setForeground(new java.awt.Color(255, 255, 255));
        DesResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesResMod.setText("0");

        ConResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ConResMod.setForeground(new java.awt.Color(255, 255, 255));
        ConResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConResMod.setText("0");

        IntResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        IntResMod.setForeground(new java.awt.Color(255, 255, 255));
        IntResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntResMod.setText("0");

        SabResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SabResMod.setForeground(new java.awt.Color(255, 255, 255));
        SabResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SabResMod.setText("0");

        CarResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CarResMod.setForeground(new java.awt.Color(255, 255, 255));
        CarResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarResMod.setText("0");

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Força");

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Destreza");

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Constituição");

        jLabel40.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Inteligência");

        jLabel38.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Sabedoria");

        jLabel37.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Carisma");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConResCheck)
                            .addComponent(IntResCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(IntResMod, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(ConResMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SabResCheck)
                            .addComponent(CarResCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SabResMod, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(CarResMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(DesResCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DesResMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ForResCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ForResMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ForResCheck)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ForResMod)
                                        .addComponent(jLabel34)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DesResCheck))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DesResMod)
                                .addComponent(jLabel35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConResCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IntResCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SabResCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarResCheck))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CarResMod)
                        .addComponent(jLabel37))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConResMod)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(IntResMod)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SabResMod)
                                    .addComponent(jLabel38))
                                .addGap(25, 25, 25)))))
                .addGap(23, 23, 23)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(23, 23, 23));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 195), 2, true));
        jPanel5.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel41.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Bônus de proficiência");

        BonusProficienciaLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BonusProficienciaLabel.setForeground(new java.awt.Color(255, 255, 255));
        BonusProficienciaLabel.setText("+0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel41)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BonusProficienciaLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BonusProficienciaLabel)
                .addGap(15, 15, 15)
                .addComponent(jLabel41)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VidaDano, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidaCura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salvarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(LevelLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(RacaSelect))
                                    .addComponent(ClassesRow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(AntecedenteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(XpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(LabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(VidaCura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(VidaDano, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(ClassesRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RacaSelect))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LevelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XpLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(AntecedenteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarBotao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarBotaoActionPerformed

    private void LabelNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelNomeActionPerformed

    }//GEN-LAST:event_LabelNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        trocarPainel mudar = new trocarPainel();
        SelectPersonagem novoFrame = new SelectPersonagem();
        mudar.painelChange(novoFrame);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VidaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VidaTotalActionPerformed

    private void AntecedenteLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntecedenteLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntecedenteLabelActionPerformed

    private void DesResCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesResCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesResCheckActionPerformed

    private void VidaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VidaAtualActionPerformed

    private void ForLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AntecedenteLabel;
    private javax.swing.JLabel BonusProficienciaLabel;
    private javax.swing.JTextField CarLabel;
    private javax.swing.JLabel CarMod;
    private javax.swing.JCheckBox CarResCheck;
    private javax.swing.JLabel CarResMod;
    private javax.swing.JLabel ClasseLabel;
    private javax.swing.JPanel ClassesRow;
    private javax.swing.JTextField ConLabel;
    private javax.swing.JLabel ConMod;
    private javax.swing.JCheckBox ConResCheck;
    private javax.swing.JLabel ConResMod;
    private javax.swing.JTextField DesLabel;
    private javax.swing.JLabel DesMod;
    private javax.swing.JCheckBox DesResCheck;
    private javax.swing.JLabel DesResMod;
    private javax.swing.JTextField ForLabel;
    private javax.swing.JLabel ForMod;
    private javax.swing.JCheckBox ForResCheck;
    private javax.swing.JLabel ForResMod;
    private javax.swing.JTextField IntLabel;
    private javax.swing.JLabel IntMod;
    private javax.swing.JCheckBox IntResCheck;
    private javax.swing.JLabel IntResMod;
    private javax.swing.JTextField LabelNome;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JLabel RacaSelect;
    private javax.swing.JTextField SabLabel;
    private javax.swing.JLabel SabMod;
    private javax.swing.JCheckBox SabResCheck;
    private javax.swing.JLabel SabResMod;
    private javax.swing.JTextField VidaAtual;
    private javax.swing.JLabel VidaCura;
    private javax.swing.JLabel VidaDano;
    private javax.swing.JTextField VidaTotal;
    private javax.swing.JTextField XpLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton salvarBotao;
    // End of variables declaration//GEN-END:variables
}
