/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import backend.jsonParser;
import backend.Fun.trocarPainel;

import static backend.Fun.Par.Geral.AlinhamentoP.AlinhamentoP;
import static backend.Fun.Par.Geral.AntecedenteP.AntecedenteP;
import static backend.Fun.Par.Geral.ClassesP.ClassesP;
import static backend.Fun.Par.Geral.JanelaP.JanelaP;
import static backend.Fun.Par.Geral.NavBarP.NavBarP;
import static backend.Fun.Par.Geral.CAP.CAP;
import static backend.Fun.Par.Geral.IniciativaP.IniciativaP;
import static backend.Fun.Par.Geral.NomeP.NomeP;
import static backend.Fun.Par.Geral.PericiasP.PericiasP;
import static backend.Fun.Par.Geral.ProfP.ProfP;
import static backend.Fun.Par.Geral.RacaP.RacaP;
import static backend.Fun.Par.Geral.ResistenciaP.ResistenciaP;
import static backend.Fun.Par.Geral.SalvarP.SalvarP;
import static backend.Fun.Par.Geral.StatusP.StatusP;
import static backend.Fun.Par.Geral.VidaP.VidaP;
import static backend.Fun.Par.Geral.XpP.XpP;
import static backend.Fun.Par.Geral.ScrollP.ScrollP;
import static backend.Fun.Par.Geral.TesteSalvamentoP.TesteSalvamentoP;
import static backend.Fun.Par.Geral.InspiracaoP.InspiracaoP;
import static backend.Fun.Par.Geral.PercepcaoPassivaP.PercepcaoPassivaP;
import static backend.Fun.Par.Geral.MovimentacaoP.MovimentacaoP;

import org.json.JSONObject;

/**
 *
 * @author Admin
 */
public class personagemFicha extends javax.swing.JFrame {

    /**
     * Creates new form personagemFicha
     *
     * @param personagem
     */
    public personagemFicha(String personagem) {
        initComponents();

        String personagemCaminho = "personagensJSON/" + personagem + ".json";
        JSONObject ficha = new JSONObject(jsonParser.LerArquivo(personagemCaminho));

        JanelaP(jPanel2);
        ScrollP(jScrollPaneGeral, jScrollPaneMochila, jScrollPaneFeiticos, jScrollPaneCarClasse);
        NavBarP(AppScrollPane, GeralNavBar, MochilaNavBar, FeiticosNavBar, CaracteristicasNavBar);
        StatusP(personagemCaminho, ForLabel, ForMod, ficha, 0);
        StatusP(personagemCaminho, DesLabel, DesMod, ficha, 1);
        StatusP(personagemCaminho, ConLabel, ConMod, ficha, 2);
        StatusP(personagemCaminho, IntLabel, IntMod, ficha, 3);
        StatusP(personagemCaminho, CarLabel, CarMod, ficha, 4);
        StatusP(personagemCaminho, SabLabel, SabMod, ficha, 5);
        ResistenciaP(personagemCaminho, ficha, ForResCheck, ForResMod, 0);
        ResistenciaP(personagemCaminho, ficha, DesResCheck, DesResMod, 1);
        ResistenciaP(personagemCaminho, ficha, ConResCheck, ConResMod, 2);
        ResistenciaP(personagemCaminho, ficha, IntResCheck, IntResMod, 3);
        ResistenciaP(personagemCaminho, ficha, SabResCheck, SabResMod, 4);
        ResistenciaP(personagemCaminho, ficha, CarResCheck, CarResMod, 5);
        TesteSalvamentoP(personagemCaminho, ficha, Sucesso1, 0);
        TesteSalvamentoP(personagemCaminho, ficha, Sucesso2, 1);
        TesteSalvamentoP(personagemCaminho, ficha, Sucesso3, 2);
        TesteSalvamentoP(personagemCaminho, ficha, Fracesso1, 3);
        TesteSalvamentoP(personagemCaminho, ficha, Fracesso2, 4);
        TesteSalvamentoP(personagemCaminho, ficha, Fracesso3, 5);

        ProfP(ficha, BonusProficienciaLabel);
        VidaP(personagemCaminho, ficha, VidaAtual, VidaTotal, VidaCura, VidaDano);
        SalvarP(ficha, salvarBotao, personagemCaminho);
        NomeP(personagemCaminho, ficha, LabelNome);
        ClassesP(personagemCaminho, ficha, ClasseLabel, ClasseLabel, personagem, LevelLabel);
        RacaP(personagemCaminho, ficha, RacaSelect);
        AlinhamentoP(personagemCaminho, ficha, AlinhamentoSelect);
        XpP(personagemCaminho, ficha, XpLabel);
        AntecedenteP(personagemCaminho, ficha, AntecedenteLabel);
        PericiasP(personagemCaminho, ficha, PericiasContainer);
        CAP(ficha, BonusCALabel);
        IniciativaP(ficha, BonusIniciativaLabel);
        InspiracaoP(personagemCaminho, ficha, InspiracaoLabel);
        PercepcaoPassivaP(ficha, PercepcaoPassivaLabel);
        MovimentacaoP(personagemCaminho, ficha, MovimentacaoText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        GeralNavBar = new javax.swing.JLabel();
        MochilaNavBar = new javax.swing.JLabel();
        FeiticosNavBar = new javax.swing.JLabel();
        CaracteristicasNavBar = new javax.swing.JLabel();
        AppScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneGeral = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LabelNome = new javax.swing.JTextField();
        salvarBotao = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ForMod = new javax.swing.JLabel();
        DesMod = new javax.swing.JLabel();
        ConMod = new javax.swing.JLabel();
        IntMod = new javax.swing.JLabel();
        SabMod = new javax.swing.JLabel();
        CarMod = new javax.swing.JLabel();
        ForLabel = new javax.swing.JTextField();
        DesLabel = new javax.swing.JTextField();
        ConLabel = new javax.swing.JTextField();
        IntLabel = new javax.swing.JTextField();
        SabLabel = new javax.swing.JTextField();
        CarLabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ClassesRow = new javax.swing.JPanel();
        ClasseLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        VidaTotal = new javax.swing.JTextField();
        VidaAtual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RacaSelect = new javax.swing.JLabel();
        LevelLabel = new javax.swing.JLabel();
        XpLabel = new javax.swing.JTextField();
        AntecedenteLabel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        PericiasContainer = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ForResCheck = new javax.swing.JCheckBox();
        DesResCheck = new javax.swing.JCheckBox();
        ConResCheck = new javax.swing.JCheckBox();
        IntResCheck = new javax.swing.JCheckBox();
        SabResCheck = new javax.swing.JCheckBox();
        CarResCheck = new javax.swing.JCheckBox();
        ForResMod = new javax.swing.JLabel();
        DesResMod = new javax.swing.JLabel();
        ConResMod = new javax.swing.JLabel();
        IntResMod = new javax.swing.JLabel();
        SabResMod = new javax.swing.JLabel();
        CarResMod = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        BonusProficienciaLabel = new javax.swing.JLabel();
        VidaCura = new javax.swing.JLabel();
        VidaDano = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        AlinhamentoSelect = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        BonusIniciativaLabel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        BonusCALabel = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Sucesso1 = new javax.swing.JCheckBox();
        Sucesso2 = new javax.swing.JCheckBox();
        Sucesso3 = new javax.swing.JCheckBox();
        Fracesso1 = new javax.swing.JCheckBox();
        Fracesso2 = new javax.swing.JCheckBox();
        Fracesso3 = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        InspiracaoLabel = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        PercepcaoPassivaLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        MovimentacaoText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPaneMochila = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPaneFeiticos = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPaneCarClasse = new javax.swing.JScrollPane();
        jPanel17 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(23, 23, 23));

        jPanel7.setBackground(new java.awt.Color(53, 53, 53));

        GeralNavBar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        GeralNavBar.setForeground(new java.awt.Color(255, 255, 255));
        GeralNavBar.setText("Geral");
        GeralNavBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MochilaNavBar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        MochilaNavBar.setForeground(new java.awt.Color(255, 255, 255));
        MochilaNavBar.setText("Mochila");
        MochilaNavBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        FeiticosNavBar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        FeiticosNavBar.setForeground(new java.awt.Color(255, 255, 255));
        FeiticosNavBar.setText("Feitiços");
        FeiticosNavBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CaracteristicasNavBar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        CaracteristicasNavBar.setForeground(new java.awt.Color(255, 255, 255));
        CaracteristicasNavBar.setText("Caracteristicas de classe");
        CaracteristicasNavBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GeralNavBar)
                .addGap(34, 34, 34)
                .addComponent(MochilaNavBar)
                .addGap(34, 34, 34)
                .addComponent(FeiticosNavBar)
                .addGap(34, 34, 34)
                .addComponent(CaracteristicasNavBar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GeralNavBar)
                        .addComponent(MochilaNavBar))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FeiticosNavBar)
                        .addComponent(CaracteristicasNavBar)))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        AppScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AppScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));

        jScrollPaneGeral.setBorder(null);
        jScrollPaneGeral.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneGeral.setPreferredSize(new java.awt.Dimension(672, 438));

        jPanel2.setBackground(new java.awt.Color(23, 23, 23));
        jPanel2.setPreferredSize(new java.awt.Dimension(672, 1950));

        jButton1.setBackground(new java.awt.Color(79, 79, 79));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("voltar para seleção");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(35, 35, 195));
        jSeparator1.setForeground(new java.awt.Color(35, 35, 195));

        LabelNome.setBackground(new java.awt.Color(23, 23, 23));
        LabelNome.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        LabelNome.setForeground(new java.awt.Color(255, 255, 255));
        LabelNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LabelNome.setText("Nome");
        LabelNome.setBorder(null);
        LabelNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelNomeActionPerformed(evt);
            }
        });

        salvarBotao.setBackground(new java.awt.Color(79, 79, 79));
        salvarBotao.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        salvarBotao.setForeground(new java.awt.Color(255, 255, 255));
        salvarBotao.setText("Salvar alterações");
        salvarBotao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carisma");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 30));

        jLabel7.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sabedoria");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, 30));

        jLabel9.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Inteligência");
        jLayeredPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        jLabel11.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Constituição");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, 30));

        jLabel13.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Destreza");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jLabel15.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Força");
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        ForMod.setForeground(new java.awt.Color(255, 255, 255));
        ForMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForMod.setText("0");
        jLayeredPane1.add(ForMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 20, 24));

        DesMod.setForeground(new java.awt.Color(255, 255, 255));
        DesMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesMod.setText("0");
        jLayeredPane1.add(DesMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 20, 24));

        ConMod.setForeground(new java.awt.Color(255, 255, 255));
        ConMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConMod.setText("0");
        jLayeredPane1.add(ConMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 20, 24));

        IntMod.setForeground(new java.awt.Color(255, 255, 255));
        IntMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntMod.setText("0");
        jLayeredPane1.add(IntMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 20, 24));

        SabMod.setForeground(new java.awt.Color(255, 255, 255));
        SabMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SabMod.setText("0");
        jLayeredPane1.add(SabMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 20, 24));

        CarMod.setForeground(new java.awt.Color(255, 255, 255));
        CarMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarMod.setText("0");
        jLayeredPane1.add(CarMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 20, 24));

        ForLabel.setBackground(new java.awt.Color(23, 23, 23));
        ForLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ForLabel.setForeground(new java.awt.Color(255, 255, 255));
        ForLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ForLabel.setText("10");
        ForLabel.setBorder(null);
        ForLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ForLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        ForLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForLabelActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ForLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 70));

        DesLabel.setBackground(new java.awt.Color(23, 23, 23));
        DesLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        DesLabel.setForeground(new java.awt.Color(255, 255, 255));
        DesLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DesLabel.setText("10");
        DesLabel.setBorder(null);
        DesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DesLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(DesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 70));

        ConLabel.setBackground(new java.awt.Color(23, 23, 23));
        ConLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ConLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ConLabel.setText("10");
        ConLabel.setBorder(null);
        ConLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ConLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(ConLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, 70));

        IntLabel.setBackground(new java.awt.Color(23, 23, 23));
        IntLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        IntLabel.setForeground(new java.awt.Color(255, 255, 255));
        IntLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IntLabel.setText("10");
        IntLabel.setBorder(null);
        IntLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IntLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(IntLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 70));

        SabLabel.setBackground(new java.awt.Color(23, 23, 23));
        SabLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        SabLabel.setForeground(new java.awt.Color(255, 255, 255));
        SabLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SabLabel.setText("10");
        SabLabel.setBorder(null);
        SabLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SabLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(SabLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 100, 70));

        CarLabel.setBackground(new java.awt.Color(23, 23, 23));
        CarLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        CarLabel.setForeground(new java.awt.Color(255, 255, 255));
        CarLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarLabel.setText("10");
        CarLabel.setBorder(null);
        CarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CarLabel.setMinimumSize(new java.awt.Dimension(70, 16));
        jLayeredPane1.add(CarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 100, 100));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 100));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/ContainerStatus.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLayeredPane1.setLayer(jLabel14, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        ClassesRow.setBackground(new java.awt.Color(23, 23, 23));

        ClasseLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        ClasseLabel.setForeground(new java.awt.Color(101, 172, 219));
        ClasseLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClasseLabel.setText("Selecione a sua classe");
        ClasseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Classe:");

        javax.swing.GroupLayout ClassesRowLayout = new javax.swing.GroupLayout(ClassesRow);
        ClassesRow.setLayout(ClassesRowLayout);
        ClassesRowLayout.setHorizontalGroup(
            ClassesRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClassesRowLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(ClasseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        ClassesRowLayout.setVerticalGroup(
            ClassesRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassesRowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ClassesRowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClassesRowLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(ClasseLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setOpaque(false);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("/");

        VidaTotal.setBackground(new java.awt.Color(23, 23, 23));
        VidaTotal.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        VidaTotal.setForeground(new java.awt.Color(255, 255, 255));
        VidaTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        VidaTotal.setText("0");
        VidaTotal.setBorder(null);
        VidaTotal.setMinimumSize(new java.awt.Dimension(104, 64));
        VidaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaTotalActionPerformed(evt);
            }
        });

        VidaAtual.setBackground(new java.awt.Color(23, 23, 23));
        VidaAtual.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        VidaAtual.setForeground(new java.awt.Color(255, 255, 255));
        VidaAtual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        VidaAtual.setText("0");
        VidaAtual.setBorder(null);
        VidaAtual.setMinimumSize(new java.awt.Dimension(104, 64));
        VidaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VidaAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(VidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel39)
                .addGap(0, 0, 0)
                .addComponent(VidaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(VidaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Raça:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nível:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Antecedente:");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Xp:");

        RacaSelect.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        RacaSelect.setForeground(new java.awt.Color(101, 172, 219));
        RacaSelect.setText("Selecione");
        RacaSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LevelLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        LevelLabel.setForeground(new java.awt.Color(101, 172, 219));
        LevelLabel.setText("Selecione");

        XpLabel.setBackground(new java.awt.Color(23, 23, 23));
        XpLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        XpLabel.setForeground(new java.awt.Color(255, 255, 255));
        XpLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        XpLabel.setText("0");
        XpLabel.setBorder(null);

        AntecedenteLabel.setBackground(new java.awt.Color(23, 23, 23));
        AntecedenteLabel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        AntecedenteLabel.setForeground(new java.awt.Color(101, 172, 219));
        AntecedenteLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        AntecedenteLabel.setText("Digite seu antecedente");
        AntecedenteLabel.setBorder(null);
        AntecedenteLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntecedenteLabelActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(23, 23, 23));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 195), 2, true));

        PericiasContainer.setOpaque(false);

        javax.swing.GroupLayout PericiasContainerLayout = new javax.swing.GroupLayout(PericiasContainer);
        PericiasContainer.setLayout(PericiasContainerLayout);
        PericiasContainerLayout.setHorizontalGroup(
            PericiasContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        PericiasContainerLayout.setVerticalGroup(
            PericiasContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Pericias:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(PericiasContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addGap(15, 15, 15)
                .addComponent(PericiasContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(23, 23, 23));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 195), 2, true));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Testes de resistência:");

        ForResCheck.setForeground(new java.awt.Color(255, 255, 255));

        DesResCheck.setForeground(new java.awt.Color(255, 255, 255));
        DesResCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesResCheckActionPerformed(evt);
            }
        });

        ConResCheck.setForeground(new java.awt.Color(255, 255, 255));

        IntResCheck.setForeground(new java.awt.Color(255, 255, 255));

        SabResCheck.setForeground(new java.awt.Color(255, 255, 255));

        CarResCheck.setForeground(new java.awt.Color(255, 255, 255));

        ForResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ForResMod.setForeground(new java.awt.Color(255, 255, 255));
        ForResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForResMod.setText("0");

        DesResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        DesResMod.setForeground(new java.awt.Color(255, 255, 255));
        DesResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DesResMod.setText("0");

        ConResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ConResMod.setForeground(new java.awt.Color(255, 255, 255));
        ConResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConResMod.setText("0");

        IntResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        IntResMod.setForeground(new java.awt.Color(255, 255, 255));
        IntResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntResMod.setText("0");

        SabResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SabResMod.setForeground(new java.awt.Color(255, 255, 255));
        SabResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SabResMod.setText("0");

        CarResMod.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CarResMod.setForeground(new java.awt.Color(255, 255, 255));
        CarResMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarResMod.setText("0");

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Força");

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Destreza");

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Constituição");

        jLabel40.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Inteligência");

        jLabel38.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Sabedoria");

        jLabel37.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Carisma");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConResCheck)
                            .addComponent(IntResCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(IntResMod, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(ConResMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SabResCheck)
                            .addComponent(CarResCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SabResMod, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(CarResMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(DesResCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DesResMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ForResCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ForResMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ForResCheck)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ForResMod)
                                        .addComponent(jLabel34)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DesResCheck))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DesResMod)
                                .addComponent(jLabel35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConResCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IntResCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SabResCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarResCheck))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CarResMod)
                        .addComponent(jLabel37))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConResMod)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(IntResMod)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SabResMod)
                                    .addComponent(jLabel38))
                                .addGap(25, 25, 25)))))
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addGap(15, 15, 15))
        );

        jPanel5.setBackground(new java.awt.Color(23, 23, 23));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(35, 35, 195)));
        jPanel5.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel41.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Bônus de proficiência");

        BonusProficienciaLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BonusProficienciaLabel.setForeground(new java.awt.Color(255, 255, 255));
        BonusProficienciaLabel.setText("+0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel41)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BonusProficienciaLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BonusProficienciaLabel)
                .addGap(15, 15, 15)
                .addComponent(jLabel41)
                .addGap(15, 15, 15))
        );

        VidaCura.setForeground(new java.awt.Color(255, 255, 255));
        VidaCura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VidaCura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/up.png"))); // NOI18N
        VidaCura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        VidaDano.setForeground(new java.awt.Color(255, 255, 255));
        VidaDano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VidaDano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/down.png"))); // NOI18N
        VidaDano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Alinhamento:");

        AlinhamentoSelect.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        AlinhamentoSelect.setForeground(new java.awt.Color(101, 172, 219));
        AlinhamentoSelect.setText("Selecione");
        AlinhamentoSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel10.setBackground(new java.awt.Color(23, 23, 23));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(35, 35, 195)));
        jPanel10.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel43.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Iniciativa");

        BonusIniciativaLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BonusIniciativaLabel.setForeground(new java.awt.Color(255, 255, 255));
        BonusIniciativaLabel.setText("+0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BonusIniciativaLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BonusIniciativaLabel)
                .addGap(15, 15, 15)
                .addComponent(jLabel43)
                .addGap(15, 15, 15))
        );

        jPanel14.setBackground(new java.awt.Color(23, 23, 23));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(35, 35, 195)));
        jPanel14.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel44.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Classe de armadura");

        BonusCALabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BonusCALabel.setForeground(new java.awt.Color(255, 255, 255));
        BonusCALabel.setText("10");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BonusCALabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BonusCALabel)
                .addGap(15, 15, 15)
                .addComponent(jLabel44)
                .addGap(15, 15, 15))
        );

        jPanel19.setBackground(new java.awt.Color(23, 23, 23));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(35, 35, 195), 2, true));
        jPanel19.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel46.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Testes de Salvamento");

        jLabel47.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Sucessos:");

        jLabel48.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Fracessos:");

        Sucesso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sucesso1ActionPerformed(evt);
            }
        });

        Sucesso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sucesso2ActionPerformed(evt);
            }
        });

        Sucesso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sucesso3ActionPerformed(evt);
            }
        });

        Fracesso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fracesso1ActionPerformed(evt);
            }
        });

        Fracesso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fracesso2ActionPerformed(evt);
            }
        });

        Fracesso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fracesso3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(Sucesso1)
                        .addGap(18, 18, 18)
                        .addComponent(Sucesso2))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Fracesso1)
                        .addGap(18, 18, 18)
                        .addComponent(Fracesso2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fracesso3)
                    .addComponent(Sucesso3))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(Sucesso1))
                    .addComponent(Sucesso2)
                    .addComponent(Sucesso3))
                .addGap(14, 14, 14)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48)
                    .addComponent(Fracesso1)
                    .addComponent(Fracesso2)
                    .addComponent(Fracesso3))
                .addGap(15, 15, 15)
                .addComponent(jLabel46)
                .addGap(15, 15, 15))
        );

        jPanel18.setBackground(new java.awt.Color(23, 23, 23));
        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(35, 35, 195)));
        jPanel18.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel45.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Inspiração");

        InspiracaoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/res/Unchecked.png"))); // NOI18N
        InspiracaoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(InspiracaoLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(InspiracaoLabel)
                .addGap(15, 15, 15)
                .addComponent(jLabel45)
                .addGap(15, 15, 15))
        );

        jPanel21.setBackground(new java.awt.Color(23, 23, 23));
        jPanel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(35, 35, 195)));
        jPanel21.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel50.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Percepção Passiva");

        PercepcaoPassivaLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        PercepcaoPassivaLabel.setForeground(new java.awt.Color(255, 255, 255));
        PercepcaoPassivaLabel.setText("10");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel50)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PercepcaoPassivaLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PercepcaoPassivaLabel)
                .addGap(15, 15, 15)
                .addComponent(jLabel50)
                .addGap(15, 15, 15))
        );

        jPanel12.setBackground(new java.awt.Color(23, 23, 23));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(35, 35, 195)));
        jPanel12.setPreferredSize(new java.awt.Dimension(221, 221));

        jLabel51.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Deslocamento");

        MovimentacaoText.setBackground(new java.awt.Color(23, 23, 23));
        MovimentacaoText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        MovimentacaoText.setForeground(new java.awt.Color(255, 255, 255));
        MovimentacaoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MovimentacaoText.setText("0.0");
        MovimentacaoText.setBorder(null);
        MovimentacaoText.setMinimumSize(new java.awt.Dimension(104, 64));
        MovimentacaoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentacaoTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel51)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(MovimentacaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(MovimentacaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel51)
                .addGap(15, 15, 15))
        );

        jSeparator2.setBackground(new java.awt.Color(35, 35, 195));
        jSeparator2.setForeground(new java.awt.Color(35, 35, 195));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VidaDano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VidaCura))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(AlinhamentoSelect)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(LabelNome)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(LevelLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(RacaSelect))
                            .addComponent(ClassesRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(AntecedenteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(XpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salvarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(LabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ClassesRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(RacaSelect))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(LevelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(XpLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(AlinhamentoSelect))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(AntecedenteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(VidaCura)
                        .addGap(0, 0, 0)
                        .addComponent(VidaDano)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(salvarBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        jScrollPaneGeral.setViewportView(jPanel2);

        jScrollPaneMochila.setBorder(null);
        jScrollPaneMochila.setPreferredSize(new java.awt.Dimension(672, 438));

        jPanel15.setBackground(new java.awt.Color(23, 23, 23));
        jPanel15.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Mochila");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(277, 277, 277))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneMochila.setViewportView(jPanel15);

        jScrollPaneFeiticos.setBorder(null);
        jScrollPaneFeiticos.setPreferredSize(new java.awt.Dimension(672, 438));

        jPanel16.setBackground(new java.awt.Color(23, 23, 23));
        jPanel16.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Feitiços");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(277, 277, 277))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneFeiticos.setViewportView(jPanel16);

        jScrollPaneCarClasse.setBorder(null);
        jScrollPaneCarClasse.setPreferredSize(new java.awt.Dimension(672, 438));

        jPanel17.setBackground(new java.awt.Color(23, 23, 23));
        jPanel17.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Caracteristicas de Classe");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(277, 277, 277))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneCarClasse.setViewportView(jPanel17);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPaneGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneMochila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneFeiticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneCarClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneMochila, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneGeral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneFeiticos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneCarClasse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        AppScrollPane.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AppScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AppScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarBotaoActionPerformed

    private void LabelNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelNomeActionPerformed

    }//GEN-LAST:event_LabelNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        trocarPainel mudar = new trocarPainel();
        SelectPersonagem novoFrame = new SelectPersonagem();
        mudar.painelChange(novoFrame);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VidaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VidaTotalActionPerformed

    private void AntecedenteLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntecedenteLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntecedenteLabelActionPerformed

    private void DesResCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesResCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesResCheckActionPerformed

    private void VidaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VidaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VidaAtualActionPerformed

    private void ForLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForLabelActionPerformed

    private void Sucesso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sucesso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sucesso1ActionPerformed

    private void Sucesso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sucesso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sucesso2ActionPerformed

    private void Sucesso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sucesso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sucesso3ActionPerformed

    private void Fracesso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fracesso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fracesso1ActionPerformed

    private void Fracesso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fracesso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fracesso2ActionPerformed

    private void Fracesso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fracesso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fracesso3ActionPerformed

    private void MovimentacaoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentacaoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovimentacaoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personagemFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlinhamentoSelect;
    private javax.swing.JTextField AntecedenteLabel;
    private javax.swing.JScrollPane AppScrollPane;
    private javax.swing.JLabel BonusCALabel;
    private javax.swing.JLabel BonusCALabel1;
    private javax.swing.JLabel BonusIniciativaLabel;
    private javax.swing.JLabel BonusProficienciaLabel;
    private javax.swing.JTextField CarLabel;
    private javax.swing.JLabel CarMod;
    private javax.swing.JCheckBox CarResCheck;
    private javax.swing.JLabel CarResMod;
    private javax.swing.JLabel CaracteristicasNavBar;
    private javax.swing.JLabel ClasseLabel;
    private javax.swing.JPanel ClassesRow;
    private javax.swing.JTextField ConLabel;
    private javax.swing.JLabel ConMod;
    private javax.swing.JCheckBox ConResCheck;
    private javax.swing.JLabel ConResMod;
    private javax.swing.JTextField DesLabel;
    private javax.swing.JLabel DesMod;
    private javax.swing.JCheckBox DesResCheck;
    private javax.swing.JLabel DesResMod;
    private javax.swing.JLabel FeiticosNavBar;
    private javax.swing.JTextField ForLabel;
    private javax.swing.JLabel ForMod;
    private javax.swing.JCheckBox ForResCheck;
    private javax.swing.JLabel ForResMod;
    private javax.swing.JCheckBox Fracesso1;
    private javax.swing.JCheckBox Fracesso2;
    private javax.swing.JCheckBox Fracesso3;
    private javax.swing.JLabel GeralNavBar;
    private javax.swing.JLabel InspiracaoLabel;
    private javax.swing.JTextField IntLabel;
    private javax.swing.JLabel IntMod;
    private javax.swing.JCheckBox IntResCheck;
    private javax.swing.JLabel IntResMod;
    private javax.swing.JTextField LabelNome;
    private javax.swing.JLabel LevelLabel;
    private javax.swing.JLabel MochilaNavBar;
    private javax.swing.JTextField MovimentacaoText;
    private javax.swing.JLabel PercepcaoPassivaLabel;
    private javax.swing.JPanel PericiasContainer;
    private javax.swing.JLabel RacaSelect;
    private javax.swing.JTextField SabLabel;
    private javax.swing.JLabel SabMod;
    private javax.swing.JCheckBox SabResCheck;
    private javax.swing.JLabel SabResMod;
    private javax.swing.JCheckBox Sucesso1;
    private javax.swing.JCheckBox Sucesso2;
    private javax.swing.JCheckBox Sucesso3;
    private javax.swing.JTextField VidaAtual;
    private javax.swing.JLabel VidaCura;
    private javax.swing.JLabel VidaDano;
    private javax.swing.JTextField VidaTotal;
    private javax.swing.JTextField XpLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPaneCarClasse;
    private javax.swing.JScrollPane jScrollPaneFeiticos;
    private javax.swing.JScrollPane jScrollPaneGeral;
    private javax.swing.JScrollPane jScrollPaneMochila;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton salvarBotao;
    // End of variables declaration//GEN-END:variables
}
